### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [eybmv/l-frank-baum_ozma-of-oz#1]
# General Issues:

- [x] Re-run `se typogrify .` and commit the first change in chapter 5.

- [x] Re-run `se semnticate .` and commit the changes in chapter 6.

- [x] Create a `se-lint-ignore.xml` file for lint error `t-005`. See [SEMOS 2.3](https://standardebooks.org/manual/1.8.0/single-page#2.3) for more info.

# chapte-3.xhtml:

- [x] Replace `<b>` with `<strong>` in `<p>“<b>Beware the Wheelers!</b>”</p>`.

# chapter-4.xhtml:

- [x] In the first `<blockquote>`, `<p><b>Smith &amp; Tinker’s</b></p>` should be in a `<header>` element.

- [x] In the first card, the first sentence is broken up into multiple paragraphs. It it more semantically correct to have the whole sentence in one paragraph and use `<br/>` elements to add breaks. See [SEMOS 1.1.6.1](https://standardebooks.org/manual/1.8.0/single-page#1.1.6.1) for an example.

- [x] In the page scan, it looks like `Thinks, Speaks, Acts, and Does Everything but Live.` and `All infringements will be promptly Prosecuted according to Law.` need to be in their own paragraphs.

- [x] In the first `<blockquote>`, place `Manufactured only at our Works...` in a `<footer>` element.

- [x] In the second `<blockquote>`, `<p><b>Directions for Using</b>:</p>` should be in a `<header>` element.

- [x] In the second card, place `<p><abbr>N. B.</abbr>⁠—This Mechanism is guaranteed to work perfectly for a thousand years.</p>` in a `<footer>` element.

# chapter-10.xhtml:

- [x] Replace the two-em dashes with regular em dashes in `“<i>thump!⁠⸺⁠thump!⁠⸺⁠thump!</i>”` ([SEMOS 8.7.7.7.2](https://standardebooks.org/manual/1.8.0/single-page#8.7.7.7.2)).

# chapter-11.xhtml:

- [x] It is redundant to have double quotes, singles quotes, **and** `<blockquote>` styling for quoted text. You can remove the single quotes in the chapter's verse. Make sure to put this in an [Editorial] commit.

# local.css:

- [x] Since the styling for verse and song are identical, you can simplify it as:
```
/* Song, verse */
[epub|type~="z3998:song"] p,
[epub|type~="z3998:verse"] p{
	text-align: initial;
	text-indent: 0;
}

[epub|type~="z3998:song"] p > span,
[epub|type~="z3998:verse"] p > span{
	display: block;
	padding-left: 1em;
	text-indent: -1em;
}

[epub|type~="z3998:song"] p > span + br,
[epub|type~="z3998:verse"] p > span + br{
	display: none;
}

p span.i1{
	padding-left: 2em;
	text-indent: -1em;
}
/* End song, verse */
```

- [x] Since the border styling for chapters 4 and 6 are identical, you can simplify it as:
```
#chapter-4 blockquote,
#chapter-6 blockquote{
	border: 1px solid;
	padding: 1em;
}
```

- [x] Chapters 4 and 6 need some custom CSS to recreate the card and sign. The following CSS should make the text look similar to the page scans. Make sure to check the styling in a web browser to make sure it looks good.
```
/* Card, sign */
header{
	margin-bottom: 1em;
	text-align: center;
}

#chapter-4 blockquote:first-of-type p,
#chapter-6 blockquote p{
	text-align: center;
	text-indent: 0;
}

#chapter-4 blockquote:last-of-type p{
	padding-left: 1em;
	text-indent: -1em;
}

#chapter-6 blockquote p:first-child{
	padding: 2em;
}

#chapter-4 b,
#chapter-6 b{
	text-transform: uppercase;
}

#chapter-4 footer{
	text-align: center;
}
/* End card, sign */
```

# colophon.xhtml:

- [x] Correct the title case for the painting.

**Comment by eybmv** [comment]
Do we change the title casing even if that is how the name of the art piece is originally?

**Comment by EmmaSweeney** [comment]
Yes.

**Comment by eybmv** [comment]
Thanks for all the help with the CSS -- will def reference back to this if another production like this comes up! All addressed and pushed.

**Comment by EmmaSweeney** [comment]
- [x] One more thing, re-run `se typogrify .` and commit the changes in chapters 6 and 10.
